In [1]:
import numpy as np

In [2]:
# 切片数组是原始数组的一个截图，与原始数组共享一个内存空间，可以直接修改元素值
a = np.arange(10)
print("a = ", a)

b = a[2:5]
b[0] = 200

print("a = ", a)
print("b = ", b)

a =  [0 1 2 3 4 5 6 7 8 9]
a =  [  0   1 200   3   4   5   6   7   8   9]
b =  [200   3   4]


In [4]:
# 使用整数序列作为下标获得的数组不和原始数组共享数组空间
a = np.logspace(0, 9, 10, base=2)
print("a = ", a)

i = np.arange(0, 10, 2)
print(i)

b = a[i]
print("b = ", b)
b[2] = 1.6

print("a = ", a)
print("b = ", b)

a =  [  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
[0 2 4 6 8]
b =  [  1.   4.  16.  64. 256.]
a =  [  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
b =  [  1.    4.    1.6  64.  256. ]


In [11]:
# 实验一下python中的列表？
# 切片
print("----------list try slice-----------")
a = [0,1,2,3,4,5,6,7,8,9]
b = a[0:2]
print("a = ", a)
print("b = ", b)

b[0] = 100
print("a = ", a)
print("b = ", b)

# 注：python的list中不能用序列作为下标

----------list try slice-----------
a =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
b =  [0, 1]
a =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
b =  [100, 1]


In [12]:
# 生成二维数序
print(np.arange(0, 60, 10).reshape(-1, 1) + np.arange(6))

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [13]:
# 二维数组的切片

In [23]:
# 二维数组去重，注意np.unique()的数序总是一维的
print("---------使用虚数，达到去重效果----------")
c = np.array(((1, 2), (3, 4), (5, 6), (1, 3), (3, 4), (7, 6)))
print("c = ", c)
x = c[:, 0] + c[:, 1] * 1j
print("转换成虚数", x)
print("使用np.unique, 虚数后去重", np.unique(x, return_index=True))
print("二维数组去重\n", c[np.unique(x, return_index=True)[1]])

print("----------使用tuple，set，再转换成np.array达到去重效果-----------")
print(np.array(list(set(tuple(t) for t in c))))

---------使用虚数，达到去重效果----------
c =  [[1 2]
 [3 4]
 [5 6]
 [1 3]
 [3 4]
 [7 6]]
转换成虚数 [1.+2.j 3.+4.j 5.+6.j 1.+3.j 3.+4.j 7.+6.j]
使用np.unique, 虚数后去重 (array([1.+2.j, 1.+3.j, 3.+4.j, 5.+6.j, 7.+6.j]), array([0, 3, 1, 2, 5]))
二维数组去重
 [[1 2]
 [1 3]
 [3 4]
 [5 6]
 [7 6]]
----------使用tuple，set，再转换成np.array达到去重效果-----------
[[1 2]
 [1 3]
 [5 6]
 [7 6]
 [3 4]]


In [ ]:
# 二维数组的堆叠，stack，axis的选择
# 二维数组的连接 concatenate